# Change these first
owner: Aruh1 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: pololer
    url: https://pololer.yurasu.xyz/
  - name: DDL pololer
    url: $DDLPOLOLERWEB
  - name: RDP pololer
    url: $RDPPOLOLER
    __dangerous__insecure: true
  - name: Pekmen
    url: https://pekmen.my.id/
  - name: Cloudflare 1.1.1.1
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53

status-website:
  cname: status.pololer.my.id
  logoUrl: https://azusa.kysdm.com/
  name: pololer-project
  theme: dark
  favicon: https://www.pololer.my.id/favicon.ico
  
