# Change these first
owner: Aruh1 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: pololer
    check: "tcp-ping"
    url: https://pololer.yurasu.xyz/
  - name: DDL pololer
    check: "tcp-ping"
    url: https://www.pololer.web.id/0:/
  - name: Embedded Video
    check: "tcp-ping"
    url: https://v.pololer.web.id/
  - name: Cloudflare 1.1.1.1
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53

status-website:
  cname: status.pololer.my.id
  logoUrl: https://azusa.kysdm.com/profile2.svg
  name: pololer-project
  theme: dark
  favicon: https://ptpimg.me/animated_favicon.gif
  
